steps:
# Build user-service
- name: gcr.io/cloud-builders/docker
  args: [
    "build", "-t", "europe-west3-docker.pkg.dev/$PROJECT_ID/seen-it/user-service:latest",
    "./services/user-service"
  ]

- name: gcr.io/cloud-builders/docker
  args: [
    "push", "europe-west3-docker.pkg.dev/$PROJECT_ID/seen-it/user-service:latest"
  ]

# Build movie-service
- name: gcr.io/cloud-builders/docker
  args: [
    "build", "-t", "europe-west3-docker.pkg.dev/$PROJECT_ID/seen-it/movie-service:latest",
    "./services/movie-service"
  ]

- name: gcr.io/cloud-builders/docker
  args: [
    "push", "europe-west3-docker.pkg.dev/$PROJECT_ID/seen-it/movie-service:latest"
  ]

# Build letterboxd-service
- name: gcr.io/cloud-builders/docker
  args: [
    "build", "-t", "europe-west3-docker.pkg.dev/$PROJECT_ID/seen-it/letterboxd-service:latest",
    "./services/letterboxd-service"
  ]

- name: gcr.io/cloud-builders/docker
  args: [
    "push", "europe-west3-docker.pkg.dev/$PROJECT_ID/seen-it/letterboxd-service:latest"
  ]

# Deploy to GKE
- name: gcr.io/cloud-builders/kubectl
  env:
    - CLOUDSDK_COMPUTE_REGION=europe-west3
    - CLOUDSDK_CONTAINER_CLUSTER=seen-it-cluster
  args:
    - apply
    - -f
    - ./release/kubernetes-manifests.yaml

options:
  logging: CLOUD_LOGGING_ONLY